version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo pre_build steps...
      - pip3 install -r requirements.txt
  build:
    commands:
      - python3 -m unittest discover tests
      - python3 setup.py install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: jsearch-module      
